# Generated by Django 4.0.6 on 2022-07-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at', '-title'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='updated_ad',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank='True', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
